library(nlme)

# ACHMIL + AGREUP + ANTODO + ARRELA + BROERE + BROMOL + BROSTE + CARCAR + CENJAC + CONARV + CREPIS + CRULAE + DACGLO + DAUCAR + ELYREP + ERYNGE + FALVUL + FESARU + FESRUB + FRAEXE + GALAPA + GALMOL + GALVER + GERDIS + GERROT + HIMHIR + LEUVUL + LOLPER + LOTCOR + MALSYL + MEDARA + MYORAM + ONOREP + ORCHID + PICECH + PICHIE + PLALAN + PLAMAJ + POAANG + POAPOI + POAPRA + POA.SP + POATRI + POTREP + PRIVUL + PRUVUL + RANACR + RANREP + RUBFRU + RUMACE + SALPRA + SENJAC + SONCHU + TAROFF + TRAPRA + TRICAM + TRIFLA + TRIPRA + TRIREP + VERBOF + VERPER + VICSAT

summary(lme(ACHMIL ~ Cb + Cd + Ci + Ee + Pg + Pp,
            data = dt_French_grasshoppers, random = ~ 1 | block, method = "REML", na.action = na.omit))


