int1 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_1.txt", header = TRUE, sep = "\t"))
int2 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_2.txt", header = TRUE, sep = "\t"))
int3 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_3.txt", header = TRUE, sep = "\t"))
int4 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_4.txt", header = TRUE, sep = "\t"))
int5 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_5.txt", header = TRUE, sep = "\t"))
int6 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_6.txt", header = TRUE, sep = "\t"))
int7 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_7.txt", header = TRUE, sep = "\t"))
int8 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_8.txt", header = TRUE, sep = "\t"))
int9 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_9.txt", header = TRUE, sep = "\t"))
int10 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_10.txt", header = TRUE, sep = "\t"))
int11 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_11.txt", header = TRUE, sep = "\t"))
int12 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_12.txt", header = TRUE, sep = "\t"))
int13 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_13.txt", header = TRUE, sep = "\t"))
int14 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_14.txt", header = TRUE, sep = "\t"))
int15 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_15.txt", header = TRUE, sep = "\t"))
int16 <- as.data.frame(read.table("Results/interactions_tic/structural_coex_interactions_16.txt", header = TRUE, sep = "\t"))

int <- rbind(int1, int2, int3, int4, int5, int6, int7, int8, int9, int10, int11, int12, int13, int14, int15, int16)

write.table(int, file = "Results/interactions_tic/interactions_tic.txt", sep = "\t", row.names = FALSE)