---
title: "One_step_model"
author: "Rodrigo R. Granjel"
date: "19 de junio de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

First, creating a database to explore the relative abundance of 

```{r loading data and packages and creating new dataset}
library(nlme)
library(mgcv)

French_grasshoppers_dt <- read.table(file = "C:/Users/Granjel RR/Desktop/Nico Gross/French_grasshoppers_dt_modified.txt", header = TRUE, sep = "\t")

#new dataset (one step, june 1st year to may last year)
new <- French_grasshoppers_dt[1:630, 1:74]
new1 <- French_grasshoppers_dt[2521:3150, 75:137]
new_data <- cbind(new, new1)

#up to 100%
new_data <- cbind(new_data[, 1:11], new_data[, 12:137] * 10)

## NAs for zeroes
for (i in 1:nrow(new_data)){
  for (j in 1:ncol(new_data)){
    if (is.na(new_data[i,j])){
      new_data[i,j] <- 0
    }
  }
}
rm(i, j, new, new1)
```


```{r BROERE new_data}
BRO_ERE <- new_data
data_BROERE <- new_data

for (i in 1:630){
  if (BRO_ERE$d_BROERE[i] == 0){
    data_BROERE <- data_BROERE[-c(i),]
  } else {
    # no change
  }
}

plot(data_BROERE$BROERE, data_BROERE$d_BROERE)
abline(lm(data_BROERE$d_BROERE ~ data_BROERE$BROERE))
abline(a = 0, b = 1, lty=2)

rm(i, BRO_ERE)
```

```{r model coef broere}

broere_lme_1_step <- lme(log(d_BROERE+1) ~ BROERE + ARRELA + DACGLO + DAUCAR + PLALAN + POAANG + RANACR + GALVER + TRIPRA + SALPRA + CONARV + MEDARA + Cb + Cd + Ci + Ee + Pg + Pp, random =~ 1 | unique, data = data_BROERE)

coef_broere <- t(coef(summary(broere_lme_1_step)))
print(coef_broere)

rm(broere_lme_1_step, data_BROERE)
```


```{r}
ARR_ELA <- new_data
data_ARRELA <- new_data

for (i in 1:630){
  if (ARR_ELA$d_ARRELA[i] == 0){
    data_ARRELA <- data_ARRELA[-c(i),]
  } else {
    # no change
  }
}

plot(data_ARRELA$ARRELA, data_ARRELA$d_ARRELA)
abline(lm(data_ARRELA$d_ARRELA ~ data_ARRELA$ARRELA))
abline(a = 0, b = 1, lty=2)

rm(i, ARR_ELA)
```

```{r}
arrela_lme_1_step <- lme(log(d_ARRELA+1) ~ BROERE + ARRELA + DACGLO + DAUCAR + PLALAN + POAANG + RANACR + GALVER + TRIPRA + SALPRA + CONARV + MEDARA + Cb + Cd + Ci + Ee + Pg + Pp, random =~ 1 | unique, data = data_ARRELA)

coef_arrela <- t(coef(summary(arrela_lme_1_step)))
print(coef_arrela)

rm(arrela_lme_1_step, data_ARRELA)
```

```{r}
DAC_GLO <- new_data
data_DACGLO <- new_data

for (i in 1:630){
  if (DAC_GLO$d_DACGLO[i] == 0){
    data_DACGLO <- data_DACGLO[-c(i),]
  } else {
    # no change
  }
}

plot(data_DACGLO$DACGLO, data_DACGLO$d_DACGLO)
abline(lm(data_DACGLO$d_DACGLO ~ data_DACGLO$DACGLO))
abline(a = 0, b = 1, lty=2)

rm(i, DAC_GLO)
```

```{r}
dacglo_lme_1_step <- lme(log(d_DACGLO+1) ~ BROERE + ARRELA + DACGLO + DAUCAR + PLALAN + POAANG + RANACR + GALVER + TRIPRA + SALPRA + CONARV + MEDARA + Cb + Cd + Ci + Ee + Pg + Pp, random =~ 1 | unique, data = data_DACGLO)

coef_dacglo <- t(coef(summary(dacglo_lme_1_step)))
print(coef_dacglo)

rm(dacglo_lme_1_step, data_DACGLO)
```

```{r}
DAU_CAR <- new_data
data_DAUCAR <- new_data

for (i in 1:630){
  if (DAU_CAR$d_DAUCAR[i] == 0){
    data_DAUCAR <- data_DAUCAR[-c(i),]
  } else {
    # no change
  }
}

plot(data_DAUCAR$DAUCAR, data_DAUCAR$d_DAUCAR)
abline(lm(data_DAUCAR$d_DAUCAR ~ data_DAUCAR$DAUCAR))
abline(a = 0, b = 1, lty=2)

rm(i, DAU_CAR)
```

```{r}
daucar_lme_1_step <- lme(log(d_DAUCAR+1) ~ BROERE + ARRELA + DACGLO + DAUCAR + PLALAN + POAANG + RANACR + GALVER + TRIPRA + SALPRA + CONARV + MEDARA + Cb + Cd + Ci + Ee + Pg + Pp, random =~ 1 | unique, data = data_DAUCAR)

coef_daucar <- t(coef(summary(daucar_lme_1_step)))
print(coef_daucar)

rm(daucar_lme_1_step, data_DAUCAR)
```

```{r}
PLA_LAN <- new_data
data_PLALAN <- new_data

for (i in 1:630){
  if (PLA_LAN$d_PLALAN[i] == 0){
    data_PLALAN <- data_PLALAN[-c(i),]
  } else {
    # no change
  }
}

plot(data_PLALAN$PLALAN, data_PLALAN$d_PLALAN)
abline(lm(data_PLALAN$d_PLALAN ~ data_PLALAN$PLALAN))
abline(a = 0, b = 1, lty=2)

rm(i, PLA_LAN)
```

```{r}
plalan_lme_1_step <- lme(log(d_PLALAN+1) ~ BROERE + ARRELA + DACGLO + DAUCAR + PLALAN + POAANG + RANACR + GALVER + TRIPRA + SALPRA + CONARV + MEDARA + Cb + Cd + Ci + Ee + Pg + Pp, random =~ 1 | unique, data = data_PLALAN)

coef_plalan <- t(coef(summary(plalan_lme_1_step)))
print(coef_plalan)

rm(plalan_lme_1_step, data_PLALAN)
```

```{r}
POA_ANG <- new_data
data_POAANG <- new_data

for (i in 1:630){
  if (POA_ANG$d_DACGLO[i] == 0){
    data_POAANG <- data_POAANG[-c(i),]
  } else {
    # no change
  }
}

rm(i, POA_ANG)
```

```{r}
poaang_lme_1_step <- lme(log(d_POAANG+1) ~ BROERE + ARRELA + DACGLO + DAUCAR + PLALAN + POAANG + RANACR + GALVER + TRIPRA + SALPRA + CONARV + MEDARA + Cb + Cd + Ci + Ee + Pg + Pp, random =~ 1 | unique, data = data_POAANG)

coef_poaang <- t(coef(summary(poaang_lme_1_step)))
print(coef_poaang)

rm(poaang_lme_1_step, data_POAANG)
```


```{r}
RAN_ACR <- new_data
data_RANACR <- new_data

for (i in 1:630){
  if (RAN_ACR$d_RANACR[i] == 0){
    data_RANACR <- data_RANACR[-c(i),]
  } else {
    # no change
  }
}

rm(i, RAN_ACR)
```

```{r}
ranacr_lme_1_step <- lme(log(d_RANACR+1) ~ BROERE + ARRELA + DACGLO + DAUCAR + PLALAN + POAANG + RANACR + GALVER + TRIPRA + SALPRA + CONARV + MEDARA + Cb + Cd + Ci + Ee + Pg + Pp, random =~ 1 | unique, data = data_RANACR)

coef_ranacr <- t(coef(summary(ranacr_lme_1_step)))
print(coef_ranacr)

rm(ranacr_lme_1_step, data_RANACR)
```


```{r}
DAC_GLO <- new_data
data_GALVER <- new_data

for (i in 1:630){
  if (DAC_GLO$d_GALVER[i] == 0){
    data_GALVER <- data_GALVER[-c(i),]
  } else {
    # no change
  }
}

rm(i, DAC_GLO)
```

```{r}
galver_lme_1_step <- lme(log(d_GALVER+1) ~ BROERE + ARRELA + DACGLO + DAUCAR + PLALAN + POAANG + RANACR + GALVER + TRIPRA + SALPRA + CONARV + MEDARA + Cb + Cd + Ci + Ee + Pg + Pp, random =~ 1 | unique, data = data_GALVER)

coef_galver <- t(coef(summary(galver_lme_1_step)))
print(coef_galver)

rm(galver_lme_1_step, data_GALVER)
```

```{r}
TRI_PRA <- new_data
data_TRIPRA <- new_data

for (i in 1:630){
  if (TRI_PRA$d_TRIPRA[i] == 0){
    data_TRIPRA <- data_TRIPRA[-c(i),]
  } else {
    # no change
  }
}

rm(i, TRI_PRA)
```

```{r}
tripra_lme_1_step <- lme(log(d_TRIPRA+1) ~ BROERE + ARRELA + DACGLO + DAUCAR + PLALAN + POAANG + RANACR + GALVER + TRIPRA + SALPRA + CONARV + MEDARA + Cb + Cd + Ci + Ee + Pg + Pp, random =~ 1 | unique, data = data_TRIPRA)

coef_tripra <- t(coef(summary(tripra_lme_1_step)))
print(coef_tripra)

rm(tripra_lme_1_step, data_TRIPRA)
```

```{r}
SAL_PRA <- new_data
data_SALPRA <- new_data

for (i in 1:630){
  if (SAL_PRA$d_SALPRA[i] == 0){
    data_SALPRA <- data_SALPRA[-c(i),]
  } else {
    # no change
  }
}

rm(i, SAL_PRA)
```

```{r}
salpra_lme_1_step <- lme(log(d_SALPRA+1) ~ BROERE + ARRELA + DACGLO + DAUCAR + PLALAN + POAANG + RANACR + GALVER + TRIPRA + SALPRA + CONARV + MEDARA + Cb + Cd + Ci + Ee + Pg + Pp, random =~ 1 | unique, data = data_SALPRA)

coef_salpra <- t(coef(summary(salpra_lme_1_step)))
print(coef_salpra)

rm(salpra_lme_1_step, data_SALPRA)
```

```{r}
CON_ARV <- new_data
data_CONARV <- new_data

for (i in 1:630){
  if (CON_ARV$d_CONARV[i] == 0){
    data_CONARV <- data_CONARV[-c(i),]
  } else {
    # no change
  }
}

rm(i, CON_ARV)
```

```{r}
conarv_lme_1_step <- lme(log(d_CONARV+1) ~ BROERE + ARRELA + DACGLO + DAUCAR + PLALAN + POAANG + RANACR + GALVER + TRIPRA + SALPRA + CONARV + MEDARA + Cb + Cd + Ci + Ee + Pg + Pp, random =~ 1 | unique, data = data_CONARV)

coef_conarv <- t(coef(summary(conarv_lme_1_step)))
print(coef_conarv)

rm(conarv_lme_1_step, data_CONARV)
```

```{r}
MED_ARA <- new_data
data_MEDARA <- new_data

for (i in 1:630){
  if (MED_ARA$d_MEDARA[i] == 0){
    data_MEDARA <- data_MEDARA[-c(i),]
  } else {
    # no change
  }
}

rm(i, MED_ARA)
```

```{r}
medara_lme_1_step <- lme(log(d_MEDARA+1) ~ BROERE + ARRELA + DACGLO + DAUCAR + PLALAN + POAANG + RANACR + GALVER + TRIPRA + SALPRA + CONARV + MEDARA + Cb + Cd + Ci + Ee + Pg + Pp, random =~ 1 | unique, data = data_MEDARA)

coef_medara <- t(coef(summary(medara_lme_1_step)))
print(coef_medara)

rm(medara_lme_1_step, data_MEDARA)
```

# CREATING THE VECTOR AND MATRICES

```{r vectors}
#intercept vector for each plant model
intercept_vector_plants <- c(coef_broere[1,1], coef_arrela[1,1], coef_dacglo[1,1], coef_daucar[1,1],
                             coef_plalan[1,1], coef_poaang[1,1], coef_ranacr[1,1], coef_galver[1,1],
                             coef_tripra[1,1], coef_salpra[1,1], coef_conarv[1,1], coef_medara[1,1])
print(intercept_vector_plants)

#vector of intercept errors from the models
intercept_vector_plants_error <- c(coef_broere[2,1], coef_arrela[2,1], coef_dacglo[2,1], coef_daucar[2,1],
                                   coef_plalan[2,1], coef_poaang[2,1], coef_ranacr[2,1], coef_galver[2,1],
                                   coef_tripra[2,1], coef_salpra[2,1], coef_conarv[2,1], coef_medara[2,1])
print(intercept_vector_plants_error)
```

```{r Plant_plant matrix}

plant_plant_matrix <- rbind("BROERE" = coef_broere[1,2:13], "ARRELA" = coef_arrela[1,2:13],
                            "DACGLO" = coef_dacglo[1,2:13], "DAUCAR" = coef_daucar[1,2:13],
                            "PLALAN" = coef_plalan[1,2:13], "POAANG" = coef_poaang[1,2:13],
                            "RANACR" = coef_ranacr[1,2:13], "GALVER" = coef_galver[1,2:13],
                            "TRIPRA" = coef_tripra[1,2:13], "SALPRA" = coef_salpra[1,2:13],
                            "CONARV" = coef_conarv[1,2:13], "MEDARA" = coef_medara[1,2:13])

plant_plant_matrix_error <- rbind("BROERE" = coef_broere[2,2:13], "ARRELA" = coef_arrela[2,2:13],
                                  "DACGLO" = coef_dacglo[2,2:13], "DAUCAR" = coef_daucar[2,2:13],
                                  "PLALAN" = coef_plalan[2,2:13], "POAANG" = coef_poaang[2,2:13],
                                  "RANACR" = coef_ranacr[2,2:13], "GALVER" = coef_galver[2,2:13],
                                  "TRIPRA" = coef_tripra[2,2:13], "SALPRA" = coef_salpra[2,2:13],
                                  "CONARV" = coef_conarv[2,2:13], "MEDARA" = coef_medara[2,2:13])
```

```{r Plant_grasshopper matrix}
plant_grasshopper_matrix <- rbind("BROERE" = coef_broere[1,14:19], "ARRELA" = coef_arrela[1,14:19],
                                  "DACGLO" = coef_dacglo[1,14:19], "DAUCAR" = coef_daucar[1,14:19],
                                  "PLALAN" = coef_plalan[1,14:19], "POAANG" = coef_poaang[1,14:19],
                                  "RANACR" = coef_ranacr[1,14:19], "GALVER" = coef_galver[1,14:19],
                                  "TRIPRA" = coef_tripra[1,14:19], "SALPRA" = coef_salpra[1,14:19],
                                  "CONARV" = coef_conarv[1,14:19], "MEDARA" = coef_medara[1,14:19])

plant_grasshopper_matrix_error <- rbind("BROERE" = coef_broere[2,14:19], "ARRELA" = coef_arrela[2,14:19],
                                        "DACGLO" = coef_dacglo[2,14:19], "DAUCAR" = coef_daucar[2,14:19],
                                        "PLALAN" = coef_plalan[2,14:19], "POAANG" = coef_poaang[2,14:19],
                                        "RANACR" = coef_ranacr[2,14:19], "GALVER" = coef_galver[2,14:19],
                                        "TRIPRA" = coef_tripra[2,14:19], "SALPRA" = coef_salpra[2,14:19],
                                        "CONARV" = coef_conarv[2,14:19], "MEDARA" = coef_medara[2,14:19])
```










